name: CI/CD Pipeline

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        python -m pytest tests/

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: docker build -t sivasai9849/cicd-pipeline:${{ github.sha }} .
      
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin   
      
      - name: Push Docker Image
        run: docker push sivasai9849/cicd-pipeline:${{ github.sha }}

      - name: Deploy to Railway 
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up -p a76ae5b8-de10-4b6e-9a6a-ddfec6a93782 --deployement-token $RAILWAY_TOKEN --name production