name: CI/CD Pipeline

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        python -m pytest tests/

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: docker build -t my-fastapi-app .
      
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
      - name: Push Docker Image
        run: docker push cicd-pipeline
